version: 2

sources:
  - name: raw
    database: dbt_db
    schema: raw
    tables:
      - name: employee_details
      - name: item
      - name: store

  - name: info_schema_dbt_db
    database: dbt_db
    schema: information_schema
    tables:
      - name: columns

  - name: staging
    database: dbt_db
    schema: staging
    tables:
      - name: t1
      - name: t2
      - name: t3
      - name: t4
      - name: t5
      - name: t6


