version: 2

sources:
  - name: raw
    description: Raw / source data storage schema
    schema: raw
    tables:
      - name: employee_details
        columns:
          - name: employee_id
            tests:
              - not_null
              - unique
              
      - name: item
      - name: store

  - name: info_schema_dbt_db
    description: Snowflake Information Schema
    schema: information_schema
    tables:
      - name: columns
        description: view to retrieve column names

  - name: staging
    description: Transformed tables / Intermediate layer
    schema: staging
    tables:
      - name: append_all
      - name: append_new
      - name: scd1_key_based
      - name: scd1_hashkey_based
      - name: scd2_key_based
      - name: scd2_hashkey_based
      - name: scd2_load_ephemeral
      - name: department_details
      - name: stg_employee_details

  - name: snapshot
    description: Schema to track Incremental data load
    schema: snapshot
    tables:
      - name: employee_details_snapshot
      - name: employee_details_snapshot_check

  - name: reporting
    description: Final table schema
    schema: reporting
    tables:
      - name: active_employee_details


